name: Health Check

on:
  push:

jobs:
  scheduled_health_check:
    runs-on: ubuntu-latest
    steps:
        - name: Check the deployed service URL
          uses: jtalk/url-health-check-action@v3
          with:
            url: https://fso-cicd.onggdfgfdrender.com
            max-attempts: 3
            retry-delay: 5s
        - name: Discord notification - health check on push suceeded
          uses: rjstone/discord-webhook-notify@v1
          if: ${{ (github.event_name == 'push' && success()) }}
          with:
            severity: info
            details: 'https://fso-cicd.onrender.com is healthy'
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
        - name: Discord notification - health check on push failed
          uses: rjstone/discord-webhook-notify@v1
          if: ${{ (github.event_name == 'push' && failure()) }}
          with:
            severity: error
            details: 'https://fso-cicd.onrender.com is not healthy'
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}